#!/bin/bash
function init() {
    LOCALE=(LANG LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME LC_ALL)
    LANGUAGE="zh_CN.UTF-8"
    for l in "${LOCALE[@]}" ; do
        export "$l=$LANGUAGE"
    done
    TYPE=(":tada: Add" ":fire: Drop" ":bug: Fix" ":memo: Document" ":hammer: Refactor" ":arrow_up: Bump" ":wrench: Make" ":racehorse: Optimize" ":art: Reformat")
}

# 验证当前是否为Git项目
function verify {
    git rev-parse --show-toplevel > /dev/null 2>&1
    GIT_VERIFY=$?
    if test $GIT_VERIFY != 0; then
      >&2 echo "fatal: Not a git repository (or any of the parent directories): .git"
      exit $GIT_VERIFY
    fi
}


# 消息主体
function mainMessage() {
    echo "选择您正在提交的类型:
        1. Add: 新增一个项目 e.g. 功能, 测试, 依赖
        2. Drop: 移除一个项目 e.g. 功能, 测试, 依赖
        3. Fix: 修复一个问题 e.g. bug, 文本, 事故, 误报.
        4. Document: 只包含文档的变更, e.g. 帮助文件.
        5. Refactor: 只有重构的变更.
        6. Bump: 增加某项目的版本 e.g. a 依赖.
        7. Make: 变更构建流程，工具或者设施.
        8. Optimize: 只包含性能优化的变更, e.g. 提高代码运行速度.
        9. Reformat: 只有格式样式的变更, e.g. 变更空格.
        0. quit: 退出 ( Exit )
    "
    read -e -n 1 -p "请选择相关数字选项 [0-9]> "

    if [[ $REPLY =~ ^[0-9]$ ]]; then
        if [[ $REPLY == 0 ]]; then
            echo "退出本次提交"
            exit
        fi
        type=${TYPE[$REPLY-1]}
    else
        echo "无效的输入" >&2
        exit 1
    fi
    # git fetch --tags --quiet
    VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
    echo "本次提交的范围，建议填写版本号 (最近版本"${VERSION}"):"
    read -e scope
    echo "请添加简短的，必要的对本次提交的描述:"
    read -e subject
    echo "添加一个完整提交的描述:"
    read -e body
    echo "列出本次提交解决的、可以关闭的所有相关问题，建议使用关键字 refs 、 close:"
    read -e footer
}
# 其他消息内容
function otherMessage() {
    #add Signed off by
    SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
}
# 构建消息
function build() {
    if [ -z "$*" ]; then
        ALL="-a"
    else
        ALL=$*
    fi
    MSGFILE="`git rev-parse --git-dir`COMMIT-MSG.tmp"

    echo "$type($scope): $subject" > $MSGFILE
    echo "" >> $MSGFILE
    echo "$body" >> $MSGFILE
    echo "" >> $MSGFILE
    echo "$footer" >> $MSGFILE
    echo "" >> $MSGFILE
    echo "$SOB" >> $MSGFILE

}
# 执行提交
function run() {
    GIT_COMMIT_CMD="git commit -F $MSGFILE $ALL"
    echo $GIT_COMMIT_CMD
    eval $GIT_COMMIT_CMD
}
# 清除临时文件
function clean() {
    rm -f $MSGFILE
}
case $1 in
    *)
        init
        verify
        mainMessage
        otherMessage
        build "$@"
        run
        clean

        ;;
esac
